all:
	g++ UCR_USP_suite.cpp -o UCR_USP_suite

FoG:	
	./UCR_USP_suite ../data/similarity_search/FoG/coded_data/Data.txt ../data/similarity_search/FoG/coded_data/Query1.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/FoG/coded_data/Data.txt ../data/similarity_search/FoG/coded_data/Query2.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/FoG/coded_data/Data.txt ../data/similarity_search/FoG/coded_data/Query3.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/FoG/coded_data/Data.txt ../data/similarity_search/FoG/coded_data/Query4.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/FoG/coded_data/Data.txt ../data/similarity_search/FoG/coded_data/Query5.txt 128 0.05

	./UCR_USP_suite ../data/similarity_search/FoG/Data.txt ../data/similarity_search/FoG/Query1.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/FoG/Data.txt ../data/similarity_search/FoG/Query2.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/FoG/Data.txt ../data/similarity_search/FoG/Query3.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/FoG/Data.txt ../data/similarity_search/FoG/Query4.txt 1024 0.05

PAMAP2:
	./UCR_USP_suite ../data/similarity_search/PAMAP2/coded_data/Data.txt ../data/similarity_search/PAMAP2/coded_data/Query1.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/PAMAP2/coded_data/Data.txt ../data/similarity_search/PAMAP2/coded_data/Query2.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/PAMAP2/coded_data/Data.txt ../data/similarity_search/PAMAP2/coded_data/Query3.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/PAMAP2/coded_data/Data.txt ../data/similarity_search/PAMAP2/coded_data/Query4.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/PAMAP2/coded_data/Data.txt ../data/similarity_search/PAMAP2/coded_data/Query5.txt 128 0.05

	./UCR_USP_suite ../data/similarity_search/PAMAP2/Data.txt ../data/similarity_search/PAMAP2/Query1.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/PAMAP2/Data.txt ../data/similarity_search/PAMAP2/Query2.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/PAMAP2/Data.txt ../data/similarity_search/PAMAP2/Query3.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/PAMAP2/Data.txt ../data/similarity_search/PAMAP2/Query4.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/PAMAP2/Data.txt ../data/similarity_search/PAMAP2/Query5.txt 1024 0.05

MITDB:
	./UCR_USP_suite ../data/similarity_search/MITDB/coded_data/Data.txt ../data/similarity_search/MITDB/coded_data/Query1.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/MITDB/coded_data/Data.txt ../data/similarity_search/MITDB/coded_data/Query2.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/MITDB/coded_data/Data.txt ../data/similarity_search/MITDB/coded_data/Query3.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/MITDB/coded_data/Data.txt ../data/similarity_search/MITDB/coded_data/Query4.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/MITDB/coded_data/Data.txt ../data/similarity_search/MITDB/coded_data/Query5.txt 128 0.05

	./UCR_USP_suite ../data/similarity_search/MITDB/Data.txt ../data/similarity_search/MITDB/Query1.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/MITDB/Data.txt ../data/similarity_search/MITDB/Query2.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/MITDB/Data.txt ../data/similarity_search/MITDB/Query3.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/MITDB/Data.txt ../data/similarity_search/MITDB/Query4.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/MITDB/Data.txt ../data/similarity_search/MITDB/Query5.txt 1024 0.05

ZXY-Soccer:
	./UCR_USP_suite ../data/similarity_search/ZXY-Soccer/coded_data/Data.txt ../data/similarity_search/ZXY-Soccer/coded_data/Query1.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/ZXY-Soccer/coded_data/Data.txt ../data/similarity_search/ZXY-Soccer/coded_data/Query2.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/ZXY-Soccer/coded_data/Data.txt ../data/similarity_search/ZXY-Soccer/coded_data/Query3.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/ZXY-Soccer/coded_data/Data.txt ../data/similarity_search/ZXY-Soccer/coded_data/Query4.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/ZXY-Soccer/coded_data/Data.txt ../data/similarity_search/ZXY-Soccer/coded_data/Query5.txt 128 0.05

	./UCR_USP_suite ../data/similarity_search/ZXY-Soccer/Data.txt ../data/similarity_search/ZXY-Soccer/Query1.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/ZXY-Soccer/Data.txt ../data/similarity_search/ZXY-Soccer/Query2.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/ZXY-Soccer/Data.txt ../data/similarity_search/ZXY-Soccer/Query3.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/ZXY-Soccer/Data.txt ../data/similarity_search/ZXY-Soccer/Query4.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/ZXY-Soccer/Data.txt ../data/similarity_search/ZXY-Soccer/Query5.txt 1024 0.05

REFIT:
	./UCR_USP_suite ../data/similarity_search/REFIT/coded_data/Data.txt ../data/similarity_search/REFIT/coded_data/Query1.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/REFIT/coded_data/Data.txt ../data/similarity_search/REFIT/coded_data/Query2.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/REFIT/coded_data/Data.txt ../data/similarity_search/REFIT/coded_data/Query3.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/REFIT/coded_data/Data.txt ../data/similarity_search/REFIT/coded_data/Query4.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/REFIT/coded_data/Data.txt ../data/similarity_search/REFIT/coded_data/Query5.txt 128 0.05

	./UCR_USP_suite ../data/similarity_search/REFIT/Data.txt ../data/similarity_search/REFIT/Query1.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/REFIT/Data.txt ../data/similarity_search/REFIT/Query2.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/REFIT/Data.txt ../data/similarity_search/REFIT/Query3.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/REFIT/Data.txt ../data/similarity_search/REFIT/Query4.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/REFIT/Data.txt ../data/similarity_search/REFIT/Query5.txt 1024 0.05
PPG:
	./UCR_USP_suite ../data/similarity_search/PPG/coded_data/Data.txt ../data/similarity_search/PPG/coded_data/Query1.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/PPG/coded_data/Data.txt ../data/similarity_search/PPG/coded_data/Query2.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/PPG/coded_data/Data.txt ../data/similarity_search/PPG/coded_data/Query3.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/PPG/coded_data/Data.txt ../data/similarity_search/PPG/coded_data/Query4.txt 128 0.05
	./UCR_USP_suite ../data/similarity_search/PPG/coded_data/Data.txt ../data/similarity_search/PPG/coded_data/Query5.txt 128 0.05
	
	./UCR_USP_suite ../data/similarity_search/PPG/Data.txt ../data/similarity_search/PPG/Query1.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/PPG/Data.txt ../data/similarity_search/PPG/Query2.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/PPG/Data.txt ../data/similarity_search/PPG/Query3.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/PPG/Data.txt ../data/similarity_search/PPG/Query4.txt 1024 0.05
	./UCR_USP_suite ../data/similarity_search/PPG/Data.txt ../data/similarity_search/PPG/Query5.txt 1024 0.05